rmdir /S /Q .\.vs
rmdir /S /Q .\EpubReader\Source\VersOne.Epub\bin
rmdir /S /Q .\EpubReader\Source\VersOne.Epub\obj
rmdir /S /Q .\HtmlToFlowDocument\HtmlToFlowDocument\bin
rmdir /S /Q .\HtmlToFlowDocument\HtmlToFlowDocument\obj
rmdir /S /Q .\HtmlToFlowDocument\HtmlToFlowDocument.Wpf\bin
rmdir /S /Q .\HtmlToFlowDocument\HtmlToFlowDocument.Wpf\obj
rmdir /S /Q .\LediReader\bin
rmdir /S /Q .\LediReader\obj
rmdir /S /Q .\SlobViewer\bin
rmdir /S /Q .\SlobViewer\obj
